export const faculty_initial_val = {
  userType: "",
  firstName: "",
  lastName: "",
  middleName: "",
  preSchool: " ",
  address: "",
  area: "",
  city: "",
  district: "",
  state: "",
  zipCode: "",
  experience: "",
  salary: "",
  subject: "",
  dob: "2000-01-01",
  bloodGroup: "",
  phoneNumber: "",
  reference: "",
  joiningDate: "2000-01-01",
  leavingDate: "2000-01-01",
  email: "",
  profilePhoto: "",
  standard: "",
  country: "",
};
